#ifndef SYSTEM_EVENT_H
#define SYSTEM_EVENT_H

#include <stdint.h>

typedef enum
{
    FAULT_NONE = 0,
    FAULT_SENSOR_DISCONNECTED,
    FAULT_SENSOR_SHORT_TO_GND,
    FAULT_SENSOR_SHORT_TO_VREF,
    FAULT_SENSOR_STUCK,
    FAULT_SENSOR_NOISY,
    FAULT_ADC_READ_FAILED,
    FAULT_UART_RX_OVERFLOW,
    FAULT_UART_HW_ERROR,
    FAULT_UART_COMMAND_SPAM,
    FAULT_BUTTON_STUCK,
    FAULT_EVENT_QUEUE_OVERFLOW
} FaultCode_t;

typedef enum
{
    FAULT_SOURCE_NONE = 0,
    FAULT_SOURCE_SENSOR,
    FAULT_SOURCE_UART,
    FAULT_SOURCE_BUTTON,
    FAULT_SOURCE_EVENT_QUEUE
} FaultSource_t;

typedef enum
{
    SYSTEM_EVENT_NONE = 0,
    SYSTEM_EVENT_SENSOR_NORMAL,
    SYSTEM_EVENT_SENSOR_WARNING,
    SYSTEM_EVENT_SENSOR_ALERT,
    SYSTEM_EVENT_FAULT_DETECTED,
    SYSTEM_EVENT_FAULT_RESET_REQUEST,
    SYSTEM_EVENT_SLEEP_REQUEST,
    SYSTEM_EVENT_MONITOR_REQUEST,
    SYSTEM_EVENT_UART_INVALID_COMMAND,
    SYSTEM_EVENT_BUTTON_SHORT_PRESS,
    SYSTEM_EVENT_BUTTON_LONG_PRESS
} SystemEventType_t;

typedef struct
{
    SystemEventType_t type;
    FaultCode_t fault;
    FaultSource_t source;
} SystemEvent_t;

#endif /* SYSTEM_EVENT_H */
